services:
  - type: web
    name: huntech-web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: huntech-db
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: tu_contrase√±a
      - key: DB_NAME
        value: huntechdb

  - type: pserv
    name: huntech-db
    env: docker
    plan: free
    dockerfilePath: ./mysql.Dockerfile
    disk:
      name: huntech-disk
      mountPath: /var/lib/mysql
      sizeGB: 1
